# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-22 01:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0013_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('blogText', models.TextField()),
                ('image', models.ImageField(upload_to='blogImgs/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
