# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-22 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_blogentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('precio', models.FloatField()),
                ('imagen', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='blogentry',
            name='user',
        ),
        migrations.DeleteModel(
            name='blogEntry',
        ),
    ]
