# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-27 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20170727_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='descripcion',
            new_name='titulo',
        ),
    ]
