# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-27 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20170727_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='titulo',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
