# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-28 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20170727_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='archivo',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
    ]
