# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-28 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_remove_post_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='chismes_de',
            field=models.CharField(choices=[('Alumno', 'Alumno'), ('Profesor', 'Profesor'), ('Otros', 'Otros')], default='Alumno', max_length=20),
        ),
    ]
