# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-28 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_remove_document_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='texto',
            field=models.TextField(blank=True),
        ),
    ]
