# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-30 22:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_auto_20170730_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
